apiVersion: v1
kind: Namespace
metadata:
  name: tilines   # <- Reemplaza con el namespace que quieras usar

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proyectoweb
  namespace: tilines
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proyectoweb
  template:
    metadata:
      labels:
        app: proyectoweb
    spec:
      containers:
        - name: proyectoweb
          image: ghcr.io/sergiolopezayala/backend:latest   # <- IMAGEN PUBLICADA EN GHCR
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: proyectoweb
  namespace: tilines
spec:
  selector:
    app: proyectoweb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proyectoweb
  namespace: tilines
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: public   # <- en MicroK8s normalmente es "public" (verifica con `kubectl get ingressclass`)
  rules:
    - host:
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: proyectoweb
                port:
                  number: 80
